baseurl: "https://blog.chungzh.cn"
languageCode: "zh-cn"
title: "Zirnc's Blog"
#theme: "hugo-tania"
theme: "klay"
paginate: 10
buildFuture: true

# disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 🎆

  # Logo will show before the blog title on site navbar.
  titleLogo: BlogFavicon16.png

  favicon: BlogFavicon16.png
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  siteName: "Zirnc's Blog"
  siteDesc: "Welcome to my blog!"
  author: "Zirnc"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: light

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email: mailto:chungzh07@gmail.com
    facebook:
    github: https://github.com/ChungZH
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram: https://t.me/skyporker_channel
    twitter: https://twitter.com/realChungZH
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: true
    provider: giscus
    giscus:
        repo: ChungZH/ChungZH.github.io
        id: MDEwOlJlcG9zaXRvcnkxNzcxMjMzNjI=
        category:
            name: Comments
            id: DIC_kwDOCo6wIs4B_i5g
        mapping: title
build:
  writeStats: true
  
menu:
  header:
    - name: 存档
      url: "/archives/"
    - name: 关于
      url: "/about/"    
    - name: 友链
      url: "/friends/"  
    - name: 标签
      url: "/tags/"
    - name: 分类
      url: "/categories/"
  footer:
    - name: RSS
      url: "/index.xml"
    - name: CC BY-NC-SA 2.5
      url: "https://creativecommons.org/licenses/by-nc-sa/2.5/cn/"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
      anchorLineNos: false
      codeFences: true
      guessSyntax: false
      hl_Lines: ""
      hl_inline: false
      lineAnchors: ""
      lineNoStart: 1
      lineNos: true
      lineNumbersInTable: true
      noClasses: true
      noHl: false
      style: monokailight
      tabWidth: 4

outputs:
  home: ["HTML", "RSS", "JSON"]